POST http://localhost:3001/api/notes HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndpbGRUdW5kZSIsImlkIjoiNjRkYzk5MjY1ZmE4YWViMzBmNjI2Y2UyIiwiaWF0IjoxNjkyMjA2ODU4LCJleHAiOjE2OTIyMTA0NTh9.K5n6OLRoTro1Yby01SvGn-8321qTxaELrGXebipev-k

{
    "content": "Farabale jojpj ",
    "important": "false"  
}

###
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "wildTunde",
    "name": "tunde pounder",
    "password": "dtsaged"
}

###

POST http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "wildTunde", 
    "password": "dtsaged"
}

###

GET http://localhost:3001/api/notes HTTP/1.1

###
DELETE http://localhost:3001/api/notes/64621a2fabaa36e345520caf HTTP/1.1

###
GET http://localhost:3001/api/notes/6467012f11e922219299eb30 HTTP/1.1

###
PUT  http://localhost:3001/api/notes HTTP/1.1
Content-Type: application/json

{
    "content": "It is a good day, I will do my best",
    "important": false
}
