POST http://localhost:3001/api/notes HTTP/1.1
Content-Type: application/json

{
    "content": "It is a good day, I will do my best",
    "important": true
}

###
GET http://localhost:3001/api/notes HTTP/1.1

###
DELETE http://localhost:3001/api/notes/64621a2fabaa36e345520caf HTTP/1.1

###
GET http://localhost:3001/api/notes/6467012f11e922219299eb30 HTTP/1.1

###
PUT  http://localhost:3001/api/notes HTTP/1.1
Content-Type: application/json

{
    "content": "It is a good day, I will do my best",
    "important": false
}
