GET http://localhost:3001/api/persons HTTP/1.1

###
GET http://localhost:3001/api/persons/648fe2b82a847ed91192c9f7 HTTP/1.1

###
DELETE http://localhost:3001/api/persons/648c74b33572842fa21f99bf HTTP/1.1

###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Adelugba Folake",
    "number": "07465-352-87645"   
}

###
GET http://localhost:3001/info HTTP/1.1
