GET http://localhost:3001/api/persons HTTP/1.1

###
DELETE http://localhost:3001/api/persons/3 HTTP/1.1

###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Toluwanimi",
    "number": "0822-332-8595"
}

###
GET http://localhost:3001/info HTTP/1.1
